project:
  type: book
  output-dir: output


book:
  title: "Theory of Computation: An Introduction For Programmers"
  cover-image: book/cover.svg
  favicon: book/favicon.png
  twitter-card: true
  
  author: 
    - name: "Shaun D. Ramsey, Ph.D."
  date: "4/2/2026"
  chapters:
    - index.qmd
    - book/status.qmd
    - book/acknowledgements.qmd
    - book/dedication.qmd
    - part: Part I - Sets and Regular Languages
      chapters:
        - I/sets.qmd
        - I/dfas.qmd
        - I/rfas.qmd
    - part: Part II - Context-Free Languages
      chapters:
        - II/context-free-languages.qmd
    - part: Part III - Turing Machines and Computability
      chapters:
        - III/turing-machines.qmd
    - book/references.qmd

bibliography: references.bib

filters:
  - diagram

lightbox: true
format:
  html:
    default-image-extension: svg
    diagram:
        format: svg
    theme:
      light:
        - cosmo
        - brand
      dark:
        - darkly
  pdf:
    default-image-extension: tex
    documentclass: scrreprt


