# Regular Expressions (REX)

In this chapter, we introduce, yet another construct, regular expressions (REX). REX are generally used more often in human contexts. Even so, they can become incredibly complicated. Often REX are seen in a variety of computing contexts from searching, verification (is this a valid email address?), and in lexical analysis. Lexical analysis is the first step your compiler or interpreter might take to translate your code into machine code. In English it might be akin to denoting each part of the sentence by its tags like "SUBJECT", "VERB", "NOUN". In a programming language it might break "a = 3;", into "VARIABLE", "ASSIGNMENT_EXPRESSION", and "INTEGER_LITERAL". In a search, we often use a wildcard, like an asterisk, to "get everything." However, a deeper understanding of regular expressions allow our searches to be more specific and powerful.

::: {.callout-important}
## Learning Objectives
- Elements of Regular Expressions (REX)
- Understanding Existing REX
- Strategies to Construct REX
:::

## Regular Expressions

A regular expression describes a language, or set of strings, much like our existing machines. However, a regular expression is constructed by a series of concatenations, unions, and optional repeats. Let's look at a simple example: a b\* + b. In this REX, a is followed by some number of bs or b is by itself. In this way, the REX describes a language. Let's break down the pieces more directly. A regular expression can consist of the following:

- any symbol from your input alphabet, a or b from the alphabet {a,b}
- ~, which represents the empty string. (a+~)b means: either "ab" or "b"
- symbols concatenated (one after another), ab means: an a followed by a b
- union or choices denoted by +, "a + b" means: either a or b
- parenthesis to group objects together, a(a+b) means: an a followed by either a or b
- repeating 0 or more times, a\* means 0 or more a's, (a+b)\* means repeat the choice of a or b - 0 or more times - abba is a valid string of this REX

These elements combine to create patterns that can accept a certain language. Let's look at some simple examples.

- A regular expression for a set of strings that begin with "01", would be written as 01(0+1)\*. This means 01 must be seen first but then can be followed by any binary string.
- A regular expression that ends with "01" would be nearly the same as (0+1)\*01. The string can be any binary string, denoted as (0+1)\*, as long as it is followed by 01.
- How about containing 01? This REX would be (0+1)\*01(0+1)\*. 01 can be preceded by any binary string or followed by any binary string, just as long as a 01 is in there somewhere.

Let's try a few:

::: {#exercise-rex .callout-note}
## Regular Expressions
- Describe the strings in the following regular expression: (aa + b)\*
- What is the shortest string in the following REX: a(ca)\*ba(ca)\*?
- Describe the strings in the following regular expression: a(ca)\*ba(ca)\*. For example, "acacacabaca" is in the language.
- Write a regular expression for strings that contain "abba".
- Write a regular expression that contains one more "na" followed by "batman". For example "nanananananananananabatman" is in the language.
- Write a regular expression for any string with an even number of 0's.
:::


We note that there are similarities in the kinds of languages we are seeing with regular expressions and our finite automata. The class of languages that these expressions and automata belong to is called the class of regular languages. In the next two chapters, we'll show, by construction, that regular expressions can be converted into NFAs and that any NFA can be converted into a REX. This will show that NFAs, DFAs, and REX have the some power of expression and recognize the same kinds of languages. As humans, and developers, we most often use REX for searching in some space (find me everything that contains "kid"), validating form fields (does the entry look like an email address), and lexical analysis. Since REX, NFAs, and DFAs all have the same power, the implementation of a REX can be done, under the hood as a DFA. In practice, this means REX can be implemented with a minified DFA very efficiently or through a power set simulation. Some REX implementations, however, use a recursive backtracking tree-based algorithm based on a REX's NFA, leading to potentially poor performance in some cases. While beyond the scope of this book, we encourage you to read on about the history and implementation of such things in @cox2007. 

Now it is time to try our hand at some exercises.

::: {#exercise-rex.callout-note}
## Exercises

- Given that n represents any digit, give a regular expression that matches a telephone number with an area code. Use dashes to separate area code and central office code. For example: 555-555-5555 is a string in the language. However, your REX can use n to represent 0+1+2+3+4+5+6+7+8+9.

- Given an alphabet of {a, @, .}, make a regular expression that includes an a, followed by 0 or more ".a" strings, followed by "@", followed by an a and one or more ".a" strings. The shortest string in the language is "a@a.a". Two more example strings are "a@a.a.a" and "a.a.a@a.a.a.a.a".

- Give a regular expression for an identifier. Do not worry about ignoring keywords. Example strings in the language include: "my_list", "_myVar", and "speed4". You may use n to represent any digit, and z to represent any character in your REX for simplicity.

- Give a REX for a string that starts and ends with a 1 and contains at least one other 1. The smallest string in this language is "111", but it also contains "10011011101".

- What is the language of 0+(1+0)\*?

- What is the language of (0+1)\*(101+111)?

- What is the language of (0+1)\*(11 + 00)(1+~)(0+1)\* ?

:::